title: Helloo
theme: minima
author: msn-05
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Idk what I am doing here ğŸ˜
# social links
github_username:  msn-05 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
